# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/Gerg-L/nix-index-database/releases/download/2024-06-09-005928/index-";
  hashes = {
    x86_64-linux = "sha256-cGwqtfhwdgRf53ToR4b5CAc7isaYMnZN1Gt+LhGr5do=";
    aarch64-linux = "sha256-z6aEC2lQ09A7WnKF5gny/DcvFIPrYeybMoNX8KE40fY=";
    x86_64-darwin = "sha256-q2ChZvjNCsAPGpnivb8s6X6DfaUrdUbyEDiSru9m2nw=";
    aarch64-darwin = "sha256-JkQbqk/wHHGT+STATcihaMJnDwe3PdZiUheojxVfX18=";
  };
}
